#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* settings
#----------- options
option presolve_eps 1e-14;

option ipopt_options 'print_timing_statistics=yes print_level=3';
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* settings!

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* fivelink test
#----------- gait problem
problem FIVELINKTEST :
  UHZD,
  t, q, v, a, u, f, I,
  bez_tau, bez_ctls,
  g_des, gdot_des, gddot_des,
  PHC_CLCK, PHC_Q, PHC_V, PHC_A,
  VHC_CLCK, VHC_Q, VHC_V, VHC_A,
  {i1 in PHASES, i2 in CON_P[i1], i3 in GRID[i1]: i2 <= 2} CONA[i1, i2, i3],
  {i1 in PHASES, i2 in CON_V[i1], i3 in GRID[i1]} CONA[i1, i2, i3],
  {i1 in PHASES, i2 in CON_P[i1], i3 in GRID[i1]: i2 <= 2 and i3 = 0} (CONQ[i1, i2, i3], CONV[i1, i2, i3]),
  {i1 in PHASES, i2 in CON_V[i1], i3 in GRID[i1]: i3 = 0} (CONQ[i1, i2, i3], CONV[i1, i2, i3]),
  EOM,
  ODE_hK,
  ODE_DEFSTEP,
  ODE_DEFQ, ODE_COLQ, ODE_DEFV, ODE_COLV,
  ODE_DEFTIME, ODE_COLTIME,
  T0, TF,
  STEP_LENGTH, STEP_HEIGHT,
  WALKING_SPEED,
  THETA_DOT,
  SWING_FOOT_HEIGHT, GROUND_CLEARANCE,
  STANCE_POSITION_AT_0[1],
  #STANCE_POSITION_AT_0, STANCE_VELOCITY_AT_0,
  SWING_IMPACT_VELX, SWING_IMPACT_VELZ,
  BEZIER_COEFFS,
  PERIODICITY_CONSTRAINT_Q, PERIODICITY_CONSTRAINT_IME,
  PYRAMID_POINT_PLANAR_LB, PYRAMID_POINT_PLANAR_UB, NORMAL_FORCE,
  V_BNDS, A_BNDS, FC_BNDS, U_BNDS,
  F_ZERO, U_ZERO,
  TORSO_PX, TORSO_PZ, TORSO_RY, HIPS, KNEES
;

#----------- solve
solve FIVELINKTEST;
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* fivelink test!

#print {j in 1.._nvars : match(_varname[j], '^t\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^x\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^q\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^v\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^a\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^u\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^f\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^I\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^g_des\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^gdot_des\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^gddot_des\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^bez_tau\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^bez_ctls\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^ODE_hK\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^vhc_v\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^phc_v\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^bez_curve\[') > 0} : j, _varname[j], _var[j];

#- print stats
print 'AMPL', _ampl_elapsed_time, _ampl_system_time, _ampl_user_time, _ampl_time;
  # wall time = _ampl_elapsed_time + _solve_elapsed_time
print 'SOLVE', _solve_elapsed_time, _solve_system_time, _solve_user_time, _solve_time;
print 'VARS', _nvars, _snvars;
print 'CONS', _ncons, _sncons;
print 'OBJ', UHZD;
print 'STATUS', solve_result, solve_result_num, solve_exitcode, solve_message;
