#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* settings
#----------- options
option presolve_eps 1e-14;

option ipopt_options 'print_timing_statistics=yes print_level=3';
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* settings!

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* script
#----------- problem
# prob: SPOTJUMPTEST d p o
#----------- mimic Horizon structure more closely
# the strategy is to do as much of the computations at integer grid points
# while trying to remove enough constraints so that we can take advantage
# of duplicating control inputs at local grid points (noninteger values);
# this is the strategy used in the OOPAMLBenchmarks AMPL model.

#----------- create global grid points
param H_SLVR symbolic = 'RK';
param H_N = GRID_MAX;
param H_K = ODE_K[H_SLVR];

set H_GLOBAL_GRID ordered by [0, H_N] := 0..H_N;
set H_ODE_GRID ordered by [0, H_N] := 0..H_N - 1;

#----------- create local grid points (based on RK parameters)
set H_ODE_K = 1..H_K;

# helper parameters and set for creating local grid points
param H_ODE_a0 = ODE_a0[H_SLVR];
param H_ODE_aK = ODE_aK[H_SLVR];

set H_ODE_STAGES := setof {i1 in H_ODE_K: 1 + H_ODE_a0 <= i1 <= H_K - H_ODE_aK} i1;

# local grid points
set H_LOCAL_GRID ordered by [0, H_N] := 
  setof {i1 in H_ODE_GRID, i2 in H_ODE_STAGES} i1 + i2 / 10;

#----------- create grid (all grid points combined)
set H_GRID ordered by [0, H_N] := H_GLOBAL_GRID union H_LOCAL_GRID;
set H_INTRMDT_GRID ordered by [0, H_N] := H_ODE_GRID union H_LOCAL_GRID;

param H_PH = 1;
set H_F = CON_P[H_PH];

set H_GRID_SWING = setof {i1 in H_ODE_GRID: i1 >= n_lo and i1 < n_td} i1;
set H_GRID_STANCE = H_ODE_GRID diff H_GRID_SWING;
set H_GRID_STANCE_VEL = H_GLOBAL_GRID diff H_GRID_SWING;

#----------- problem
problem SPOTJUMPTEST :
  JUMP,
  
  {i1 in H_GRID} (
    t[i1], 
    {i2 in Q} (q[i2, i1], v[i2, i1])
  ), 
  
  {i1 in H_INTRMDT_GRID} (
    {i2 in Q} (a[i2, i1], u[i2, i1]), 
    {i2 in H_F} f[H_PH, i2, i1]
  ),
  
  {i1 in H_F, i2 in H_GRID_STANCE} CONV[H_PH, i1, i2], 
  {i1 in Q, i2 in H_ODE_GRID} EOM[H_PH, i1, i2],
  
  {i1 in H_ODE_GRID} (ODE_hK[H_SLVR, i1], DT[H_SLVR, i1]),
  
  {i1 in Q} (
    {i2 in H_ODE_GRID} (
      ODE_DEFQ[H_SLVR, i1, i2], ODE_DEFV[H_SLVR, i1, i2],
      {i3 in H_ODE_STAGES} (
        ODE_COLQ[H_SLVR, i1, i2, i3], ODE_COLV[H_SLVR, i1, i2, i3]
      )
    )
  ),
  
  {i1 in H_ODE_GRID} (
    ODE_DEFTIME[H_SLVR, i1],
    {i2 in H_ODE_STAGES} ODE_COLTIME[H_SLVR, i1, i2]
  ),
  
  X0, XF,
  
  {i1 in X, i2 in H_GRID} XBNDS[i1, i2],
  
  {i1 in H_ODE_GRID} (
    {i2 in Q} (ABNDS[i2, i1], UBNDS[i2, i1]),
    {i2 in H_F} FBNDS[i2, i1]
  ),
  
  {i2 in H_ODE_GRID, i3 in H_ODE_STAGES} (
    {i1 in Q} (A_RK_LCL[H_SLVR, i1, i2, i3], U_RK_LCL[H_SLVR, i1, i2, i3]), 
    {i1 in H_F} F_RK_LCL[H_SLVR, i1, i2, i3]
  ),
  
  {i1 in H_F, i2 in H_GRID_SWING} NO_FORCE_DURING_JUMPING[i1, i2],
  
  {i1 in F_N, i3 in H_GRID_STANCE} (
    FC_GROUND_3[i1, i3],
    {i2 in F_T} (FC_GROUND_1[i1, i2, i3], FC_GROUND_2[i1, i2, i3])
  ),
  
  T0
;

#----------- solve
solve SPOTJUMPTEST;
if solve_result != 'solved' then {
  print 'failed!', 'SPOTJUMPTEST', '--', SPOTJUMPTEST.result, '--',  SPOTJUMPTEST.message;
}
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* script!

#print {j in 1.._nvars : match(_varname[j], '^x\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^t\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^u\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^a\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^f\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^ODE_hK\[') > 0} : j, _varname[j], _var[j];

#- print stats
print 'AMPL', _ampl_elapsed_time, _ampl_system_time, _ampl_user_time, _ampl_time;
  # wall time = _ampl_elapsed_time + _solve_elapsed_time
print 'SOLVE', _solve_elapsed_time, _solve_system_time, _solve_user_time, _solve_time;
print 'VARS', _nvars, _snvars;
print 'CONS', _ncons, _sncons;
print 'OBJ', JUMP, 3 * sum {i1 in Q, i2 in H_GLOBAL_GRID} v[i1, i2]^2
  + 0.02 * sum {i1 in H_F, i2 in H_ODE_GRID} f[1, i1, i2]^2;
print 'STATUS', solve_result, solve_result_num, solve_exitcode, solve_message;
