#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* settings
#----------- options
option presolve_eps 1e-14;
option solver knitro;

option presolve 1;
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* settings!

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* grasp test
#----------- grasp problem
problem GRASPTEST :
  NUM_FINGERS,
  q, v, a, f, c, fingers,
  {i1 in Q, i2 in GRID[0]: i1 <= nm} EOM[1, i1, i2],
  FC_NO_CONTACT, FC_NO_WRENCH, FPC,
  Q_OBJECT, V_OBJECT, A_OBJECT,
  NUM_CONTACTS, FORM_CLOSURE, MATRIX_RANK
;

#----------- solve
solve GRASPTEST;
if solve_result != 'solved' then {
  print 'failed!', 'GRASPTEST', '--', GRASPTEST.result, '--',  GRASPTEST.message;
}
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* grasp test!

#print {j in 1.._nvars : match(_varname[j], '^x\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^t\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^f\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^g\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^OSIM_X_c0\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^c\[') > 0} : j, _varname[j], _var[j];
#print {j in 1.._nvars : match(_varname[j], '^det_G\[') > 0} : j, _varname[j], _var[j];

#- print stats
print 'AMPL', _ampl_elapsed_time, _ampl_system_time, _ampl_user_time, _ampl_time;
  # wall time = _ampl_elapsed_time + _solve_elapsed_time
print 'SOLVE', _solve_elapsed_time, _solve_system_time, _solve_user_time, _solve_time;
print 'VARS', _nvars, _snvars;
print 'CONS', _ncons, _sncons;
print 'OBJ', NUM_FINGERS;
print 'STATUS', solve_result, solve_result_num, solve_exitcode, solve_message;
